In [73]:
import torch
import numpy as np

In [7]:
# Test random numbers
x = torch.rand(3)
print(x)

tensor([0.4341, 0.4925, 0.9042])


In [8]:
# Check if cuda is available
print(torch.cuda.is_available())

False


In [49]:
# Initiate torch
x = torch.empty(1)
print(x.dtype, x)
x = torch.empty(3)
print(x.dtype, x)
x = torch.empty(3, 5)
print(x.dtype, x)
x = torch.empty(2, 3, 5)
print(x.dtype, x)

x = torch.rand(2, 3)
print(x.dtype, x)

x = torch.zeros(2, 3)
print(x.dtype, x)

x = torch.ones(2, 3)
print(x.dtype, x)

# We can specify data type
# and get size
x = torch.empty(2, 3, dtype=torch.int)
print(x.dtype, x.size(), x)
x = torch.empty(2, 3, dtype=torch.double)
print(x.dtype, x.size(), x)
x = torch.empty(2, 3, dtype=torch.float16)
print(x.dtype, x.size(), x)

torch.float32 tensor([-5.6236e-18])
torch.float32 tensor([-5.6000e-18,  3.0766e-41, -5.5694e-18])
torch.float32 tensor([[ 2.8078e-34,  4.5775e-41, -5.6416e-18,  3.0766e-41,  4.4842e-44],
        [ 0.0000e+00,  8.9683e-44,  0.0000e+00, -5.6333e-18,  3.0766e-41],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])
torch.float32 tensor([[[ 2.8078e-34,  4.5775e-41, -5.6411e-18,  3.0766e-41,  1.4013e-45],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00, -5.5958e-18,  3.0766e-41, -2.2307e-18]],

        [[ 3.0766e-41, -2.1279e+00,  4.5773e-41,  1.4013e-45,  0.0000e+00],
         [ 1.1210e-44,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]])
torch.float32 tensor([[0.8723, 0.9502, 0.9154],
        [0.7606, 0.7536, 0.6647]])
torch.float32 tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.float32 tensor([[1., 1., 1.],
        [1

In [52]:
x = torch.tensor([2, 4, 6])
print(x)

tensor([2, 4, 6])


In [56]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)

# Same addition
c = a + b
d = torch.add(a, b)

print(a)
print(b)
print(c)
print(d)

# Here a will be modified
a.add_(b)
print(a)
print(b)

tensor([[0.5747, 0.4497],
        [0.7575, 0.7008]])
tensor([[0.4512, 0.9151],
        [0.1647, 0.5000]])
tensor([[1.0259, 1.3648],
        [0.9222, 1.2008]])
tensor([[1.0259, 1.3648],
        [0.9222, 1.2008]])
tensor([[1.0259, 1.3648],
        [0.9222, 1.2008]])
tensor([[0.4512, 0.9151],
        [0.1647, 0.5000]])


In [59]:
e = torch.sub(a, b)
f = torch.mul(a, b)
g = torch.div(a, b)

print(e)
print(f)
print(g)

tensor([[0.5747, 0.4497],
        [0.7575, 0.7008]])
tensor([[0.4629, 1.2490],
        [0.1518, 0.6004]])
tensor([[2.2736, 1.4914],
        [5.6003, 2.4017]])


In [68]:
# Manipulation

m = torch.rand(3, 5)
print(m)

# Select column
print(m[:, 0])
print(m[:, 1])
print(m[0, :])
print(m[0, 2:])

print(m[0, 2])
# Item can be retrived if there is only one value
print(m[0, 2].item())

tensor([[0.6536, 0.9264, 0.4468, 0.0552, 0.1663],
        [0.5036, 0.7966, 0.5775, 0.8025, 0.6062],
        [0.4017, 0.4909, 0.8385, 0.6045, 0.8961]])
tensor([0.6536, 0.5036, 0.4017])
tensor([0.9264, 0.7966, 0.4909])
tensor([0.6536, 0.9264, 0.4468, 0.0552, 0.1663])
tensor([0.4468, 0.0552, 0.1663])
tensor(0.4468)
0.44683003425598145


In [74]:
# Resizing tensors
m = torch.rand(4, 4)
print(m)

n = m.view(16)
print(n)
n = m.view(2, 8)
print(n)
n = m.view(8, 2)
print(n)
n = m.view(-1, 8) # Torch will recalculate size
print(n)

tensor([[0.5301, 0.9715, 0.3791, 0.1554],
        [0.0319, 0.5665, 0.1646, 0.6775],
        [0.9193, 0.7378, 0.2088, 0.9599],
        [0.8214, 0.2818, 0.8223, 0.2554]])
tensor([0.5301, 0.9715, 0.3791, 0.1554, 0.0319, 0.5665, 0.1646, 0.6775, 0.9193,
        0.7378, 0.2088, 0.9599, 0.8214, 0.2818, 0.8223, 0.2554])
tensor([[0.5301, 0.9715, 0.3791, 0.1554, 0.0319, 0.5665, 0.1646, 0.6775],
        [0.9193, 0.7378, 0.2088, 0.9599, 0.8214, 0.2818, 0.8223, 0.2554]])
tensor([[0.5301, 0.9715],
        [0.3791, 0.1554],
        [0.0319, 0.5665],
        [0.1646, 0.6775],
        [0.9193, 0.7378],
        [0.2088, 0.9599],
        [0.8214, 0.2818],
        [0.8223, 0.2554]])
tensor([[0.5301, 0.9715, 0.3791, 0.1554, 0.0319, 0.5665, 0.1646, 0.6775],
        [0.9193, 0.7378, 0.2088, 0.9599, 0.8214, 0.2818, 0.8223, 0.2554]])


In [77]:
# Convert to numpy
a = torch.rand(3)
print(type(a), a)

b = a.numpy()
print(type(b), b)

# Both a and b will be changed as they are directing same memory location
a.add_(1)
print(a)
print(b)

<class 'torch.Tensor'> tensor([0.0585, 0.2217, 0.4288])
<class 'numpy.ndarray'> [0.05853903 0.2216866  0.4288407 ]
tensor([1.0585, 1.2217, 1.4288])
[1.058539  1.2216866 1.4288406]


In [81]:
# Convert from numpy
a = np.ones(5)
print(type(a), a)

b = torch.from_numpy(a)
print(type(b), b)

# Both a and b will be changed as they are directing same memory location
a += 1
print(a)
print(b)

<class 'numpy.ndarray'> [1. 1. 1. 1. 1.]
<class 'torch.Tensor'> tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
